name: 'AzurePowerShellScriptToCreateSnoshot'

on:
  push:
    branches: [ main ]
    paths: .github/workflows/snapshot-ci.yml
  pull_request:
    branches:  none # [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  Azure-Powershell-Script:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
                
    - name: Login to Azure with Service Principal
      uses: Azure/login@v1.4.3
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Install Azure PowerShell 
    # uses: powershell-devops/powershell-devops@02eb25c9e71d654cf5e82f4af4b09cd7ba31054e
      uses: powershell-devops/powershell-devops@v0.2.0

    - name: Run Azure Powershell Script
      shell: pwsh
      run: |
        .\snapshot.ps1
