name: 'AzurePowerShell-Script-To-CreateSnoshot-From-VM'

on:
  push:
    branches: [ main ]
    paths: .github/workflows/snapshot-ci.yml
  pull_request:
    branches:  none # [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

jobs: 
  azurestack-test:
    runs-on: windows-latest
    steps:
    # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to AzureStack with Az Powershell
        uses: azure/login@releases/v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          environment: 'AzureStack'
          enable-AzPSSession: true

      - name: Run Az PowerShell Script 
        uses: azure/powershell@v1
        with:
          azPSVersion: "latest"
          inlineScript: |
            hostname
            Get-AzContext
            Get-AzResourceGroup

      - name: Run Azure Powershell Script
        shell: pwsh
        run: |
          .\snapshot.ps1
